
#Server Config
[server]
	#Allow models to change eye height. Will not take effect if server side is not modded or not allowed.
	customEyeHeight = true
	#Receive models that are not located at the server from clients.
	receiveModels = true
	#Allow models to change bounding box. Will not take effect if server side is not modded or not allowed.
	customBoundingBox = true

